### ISSUE TITLE
Create gem

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iecbib#1]
The task here is to create a gem with the same functionality as isobib, including scraping, but retrieving bibliographic entries the IEC website, http://www.iec.ch, instead of the  ISO website. 

From a first look at entries, the information about standards on the IEC site seems better laid out than on the ISO site.

Things to bear in mind with the IEC:

* ISO and IEC standards are meant to follow the same format and have the same governance; so I expect their bibliographic entries to be similar in format.
* The IEC like the ISO has technical committees and subcommitees and workgroups.
* IEC standards can have subparts; e.g. https://webstore.iec.ch/publication/63659 : IEC 61058-2-5:2018. Subparts are serialised as a distinct attribute from parts, so this would be rendered in XML with `<docidentifier><project-number part="2" subpart="5">IEC 61058</project-number></docidentifier>`
* The History tab points to previous versions of the same spec; "revised" should be interpreted as an "obsoletes" relation.
* For standards currently in preparation (e.g. https://webstore.iec.ch/publication/63659), the "Work in progress" tab gives the status of the publication. The status codes are listed in http://www.iec.ch/standardsdev/resources/processes/stage_codes.htm, and are meant to be aligned to the numeric codes we see in ISO; I will provide mappings below. Standards currently in preparation list the current standard they are replacing under the History tab, with its status given as Valid; that should still be treated as an "obsoletes" relation.
* Unlike ISO, IEC have an advanced search page, https://webstore.iec.ch/advsearchform, which allows much better targeted searches (we can have real searches by code and date, not just text searches). I strongly suggest we use it. For example, https://webstore.iec.ch/advsearchform?&q=&RefHeader=IEC&RefNbr=60050-102&ComNumber=&ICSNumber=&typepub=&vap=&From=2007-01-01&To=2007-12-31 , which is an actual search for IEC 60050-102:2007.

Question for @ronaldtse: IEC specs have a stability date, a date up to which the standard is guaranteed to be unchanged: https://webstore.iec.ch/webstore/webstore.nsf/xpFAQ.xsp?Open&id=ADMN-7NALM5. Do we encode this as a future "obsoleted" or "confirmed" date, or introduce a new category?

**Comment by opoudjis** [comment]
This is the mapping of IEC status codes, http://www.iec.ch/standardsdev/resources/processes/stage_codes.htm, to ISO status codes, https://www.iso.org/stage-codes.html; see also http://www.iec.ch/standardsdev/resources/processes/pdf/StageCodes_TR_v1.pdf.

@ronaldtse, could you could get a more official mapping out of IEC? They claim to be harmonised, but the mappings are not as straightforward as claimed, and I'm doing some guessing. The codes are also quite redundant, being specific to publication type. 

ACD | Approved for CD | IS, TS, TR | 20.99
ACDV | Approved for CDV | IS, TS, TR | 30.99
ADTR | Approved for DTR | TR |  40.99
ADTS | Approved for DTS | TS |  40.99
AFDIS | Approved for FDIS | IS | 40.99
APUB | Approved for publication | IS, TS, TR, PAS | 50.99
BPUB | Being published | IS, TS, TR, PAS | 60.00
CAN | Draft cancelled | IS, TS, TR, PAS | 20.98
CD | Draft circulated as CD | IS, TS, TR | 30.00
CDM | CD to be discussed at meeting | IS, TS, TR | 30.20
CCDV | Draft circulated as CDV | IS | 40.00
CDVM | Rejected CDV to be discussed at a meeting | IS | 40.93 (?)
CFDIS | Draft circulated as FDIS | IS | 50.20
CDPAS | Draft circulated as DPAS | PAS | 50.20
CDTR | Draft circulated as DTR | TR | 50.20
CDTS | Draft circulated as DTS | TS | 50.20
DTRM | Rejected DTR to be discussed at meeting | TR | 50.92
DTSM | Rejected DTS to be discussed at meeting | TS | 50.92
DECFDIS | FDIS at editing check | IS | 50.60
DECPUB | Publication at editing check | IS, TS, TR, PAS | 60.00
DEL | Deleted/abandoned | IS, TS, TR | 00.99
DELPUB | Deleted publication | IS, TS, TR, PAS | 90.99
NCDV | CDV rejected | IS | 40.98
NDTR | DTR rejected | TR | 50.98
NDTS | DTS rejected | TS | 50.98
NFDIS | FDIS rejected | IS | 50.98
PCC | Preparation of CC | IS, TS, TR
PNW | New work item proposal | IS, TS | 10.00
PPUB | Publication issued | IS, TS, TR, PAS | 60.60 (?)
PRVC | Preparation of RVC | IS | 40.92
PRVD | Preparation of RVD | IS | 40.92
PRVDPAS | Preparation of RVDPAS | PAS | 40.92
PRVDTR | Preparation of RVDTR | TR | 40.92
PRVDTS | Preparation of RVDTS | TS | 40.92
PRVN | Preparation of RVN | IS, TS | 40.92
PWI | Preliminary work item | IS, TS, TR | 00.00
RFDIS | FDIS received and registered | IS | 50.00
RPUB | Publication received and registered | IS, TS, TR, PAS | 60.60
TCDV | Translation of CDV | IS | 50.00
TDTR | Translation of DTR | TR | 50.00
TDTS | Translation of DTS | TS | 50.00
TFDIS | Translation of FDIS | IS | 50.00
TPUB | Translation of publication | IS, TS, TR | 60.00
WPUB | Publication withdrawn | IS, TS, TR, PAS | 95.99

**Comment by ronaldtse** [comment]
We could encode the date, perhaps as a “stable” date because it is not really the obsolescence date? It is a completely different concept — post stable date, there might or might not be an obsolete date and might or might not have a replacement.

**Comment by opoudjis** [comment]
It'd be lovely if it was a past participle, since all the other ones are; "guaranteed"? "unchanged"?

**Comment by andrew2net** [comment]
@opoudjis What status should we assign if there isn't a "Work in progress" tab https://webstore.iec.ch/publication/160 ?

**Comment by opoudjis** [comment]
Published, 60.60

**Comment by ronaldtse** [comment]
Agree with @opoudjis, past participle.

**Comment by opoudjis** [comment]
@ronaldtse  Are you agreeing to "guaranteed" or to "published"?

**Comment by ronaldtse** [comment]
@opoudjis I'm not sure if "guaranteed" means the same as "stability" (which is the IEC term). Perhaps "unchanged" is better.

**Comment by opoudjis** [comment]
Is the gem ready, @andrew2net?

**Comment by andrew2net** [comment]
@opoudjis IEC's relations have types `Valid`, `Revised`, `Replaced`, `Withdrawn`. How should they correlate with `BibliographicItem`'s document relation types?

**Comment by andrew2net** [comment]
@opoudjis The gem is ready. It needs IsoBibItem from Github because I added `subpart_number` attribute but didn't release a new version of the IsoBibItem gem.
Also, if it's required, we need to change IsoBibItem to_xml function to add the `subpart_number` attribute to XML output. As I see in `IsoBibItem::IsoDocumentId#to_xml` part_number is commented.

**Comment by opoudjis** [comment]
I'm doing releases, and I've made the changes to iso-bib-item. Thank you!
