### ISSUE TITLE
Add new from_xml structure

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iecbib#3]
I notice that you have reorganised the way from_xml works in isobib, ietfbib and gbbib. The reorganisation needs to take place for iecbib as well. Fortunately, iecbib should be identical to isobib in this regard: the only difference between the two is the addition of subpart for iecbib references.

**Comment by opoudjis** [comment]
Note that I'm going to delay releasing the relaton gems until this is done; the switch to reading references from XML means that there will be major releases for all gems.

**Comment by ronaldtse** [comment]
Exciting change. Hope it works :wink:

**Comment by andrew2net** [comment]
@opoudjis It's not so much reorganization for `iecbib` since it uses `iso-bib-item`'s `to_xml` function.
Done it.
